
export const BASE_CANVAS_SCALE = 2.5;
export const KERF_WIDTH_CM = 0;
export const MAX_HISTORY_STATES = 20;

export const STORAGE_KEY_PIECES = 'sheetLayoutCalcPieces_v21_offcuts_final3_modular'; 
export const STORAGE_KEY_SETTINGS = 'sheetLayoutCalcSettings_v21_offcuts_final3_modular';
export const STORAGE_KEY_ID_COUNTER = 'sheetLayoutCalcIdCounter_v21_offcuts_final3_modular';
export const STORAGE_KEY_HISTORY = 'sheetLayoutCalcHistory_v21_offcuts_final3_modular';
export const STORAGE_KEY_LANGUAGE = 'sheetLayoutCalcLang_v9_offcuts_final3_modular';
export const STORAGE_KEY_CURRENT_UNIT = 'sheetLayoutCalcUnit_v9_offcuts_final3_modular';
export const STORAGE_KEY_CUTTING_LIST_CHECKS = 'sheetLayoutCalcCutChecks_v9_offcuts_final3_modular';
export const STORAGE_KEY_PROJECTS = 'sheetLayoutCalcProjects_v8_offcuts_final3_modular'; 
export const STORAGE_KEY_GRAIN_COLOR = 'sheetLayoutCalculatorGrainColor_v3_offcuts_final3_modular';
export const STORAGE_KEY_FITTING_STRATEGY = 'sheetLayoutCalculatorFittingStrategy_v2_offcuts_final3_modular';
export const STORAGE_KEY_SAVED_OFFCUTS = 'sheetLayoutCalculatorSavedOffcuts_v3_final_modular'; 
export const STORAGE_KEY_OFFCUT_SETTINGS = 'sheetLayoutCalculatorOffcutSettings_v1_final3_modular';

export const conversionFactorsToCm = { 'cm': 1, 'mm': 0.1, 'm': 100, 'in': 2.54, 'ft': 30.48 };

export const langStrings = {
    "hi": {
        // ... (आपकी सभी हिंदी स्ट्रिंग्स यहाँ) ...
        "appTitle": "विज़ुअल शीट लेआउट कैलकुलेटर", "headerTitle": "शीट लेआउट",
        "printPdfBtn": "प्रिंट/PDF",
        "grainColorLabel": "ग्रेन का रंग:", "grainGray": "हल्का ग्रे", "grainLightBrown": "हल्का भूरा", "grainDarkBrown": "गहरा भूरा", "grainTan": "टैन", "grainNone": "कोई ग्रेन नहीं",
        "fittingStrategyLabel": "फिटिंग रणनीति चुनें:",
        "strategyDefaultScore": "डिफ़ॉल्ट स्कोर आधारित (बड़े पीस पहले)",
        "strategyMinWastage": "न्यूनतम व्यर्थ क्षेत्र",
        "strategyFirstFit": "फर्स्ट फिट (सबसे तेज़)",
        "strategyWorstFit": "वर्स्ट फिट (अधिक व्यर्थ क्षेत्र)",
        "strategyBottomLeftFree": "खाली आयत (बॉटम-लेफ्ट प्राथमिकता)",
        "strategySortPiecePerimeterDesc": "पीस: परिधि (बड़े पहले)",
        "strategySortPieceLongestSideDesc": "पीस: सबसे लंबी भुजा पहले",
        "strategySortPieceShortestSideAsc": "पीस: सबसे छोटी भुजा पहले",
        "strategySortPieceWidthDesc": "पीस: चौड़ाई (बड़े पहले)",
        "strategySortPieceHeightDesc": "पीस: ऊंचाई/लंबाई (बड़े पहले)",
        "strategySortPieceAreaAsc": "पीस: क्षेत्रफल (छोटे पहले)",
        "calculateWithStrategyBtn": "चयनित रणनीति से गणना करें",
        "useSavedOffcutsLabel": "सहेजे गए ऑफकट्स का उपयोग करें", 
        "offcutSettingsTitle": "ऑफकट सेटिंग्स", 
        "minOffcutWidthLabel": "न्यूनतम ऑफकट चौड़ाई", 
        "minOffcutLengthLabel": "न्यूनतम ऑफकट लंबाई", 
        "offcutsLibraryTitle": "ऑफकट लाइब्रेरी", 
        "noOffcutsSaved": "कोई ऑफकट सेव नहीं किया गया है।", 
        "confirmDeleteOffcut": "क्या आप वाकई इस ऑफकट को हटाना चाहते हैं?", 
        "totalUsefulOffcutsGenerated": "कुल उपयोगी ऑफकट बने:", 
        "saveUsefulOffcutsBtn": "उपयोगी ऑफकट सहेजें",
        "noUsefulOffcutsGenerated": "कोई उपयोगी ऑफकट नहीं बने।",
        "offcutsSavedBtn": "ऑफकट सहेजे गए",
        "otherSmallWastageLabel": "अन्य छोटे वेस्टेज टुकड़े:",
        "usefulOffcutsSavedAlert" : "{count} उपयोगी ऑफकट लाइब्रेरी में सहेजे गए!",
        "noNewOffcutsToSaveAlert": "कोई नया उपयोगी ऑफकट सहेजने के लिए नहीं मिला।",
        "sourceSheetNameLabel": "स्रोत शीट",
        "addManualOffcutTitle": "मैन्युअल ऑफकट जोड़ें",
        "offcutWidthLabel": "चौड़ाई",
        "offcutLengthLabel": "लंबाई",
        "offcutSourceNameLabel": "स्रोत (वैकल्पिक)",
        "offcutSourcePlaceholder": "उदा. पुरानी परियोजना",
        "addManualOffcutBtn": "ऑफकट जोड़ें",
        "alert_invalidOffcutDimensions": "कृपया मान्य ऑफकट आयाम दर्ज करें।",
        "alert_offcutAddedManually": "ऑफकट मैन्युअल रूप से जोड़ा गया!",
        "manualEntryLabel": "मैन्युअल एंट्री",
        "batchIdLabel": "बैच ID", "statusLabel": "स्थिति", "availableLabel": "उपलब्ध", "usedLabel": "प्रयुक्त",
        "confirmUseOffcutsMsg": "क्या आप {name} स्रोत वाले {count} ऑफकट (या सभी उपलब्ध {count} ऑफकट यदि कोई नाम नहीं है) का उपयोग करना चाहते हैं?",
        "noMatchingOffcuts": "इस शीट नाम के लिए कोई ऑफकट नहीं मिला, या कोई ऑफकट उपलब्ध नहीं है।",
        "unnamedSheetLabel": "अनाम शीट",
        "allSourcesLabel": "सभी स्रोतों",
        "offcutsSelectedForCalcAlert": "{count} ऑफकट गणना के लिए चुने गए।",
        "exportJson": "JSON एक्सपोर्ट करें", "importJson": "JSON इम्पोर्ट करें", "clearSavedData": "सेव डेटा क्लियर करें",
        "addPieceTitle": "पीस जोड़ें", "pieceNameLabel": "पीस का नाम (वैकल्पिक):",
        "pieceDefaultName": "पीस-",
        "pieceWidthLabel": "पीस की चौड़ाई", "pieceLengthLabel": "पीस की लंबाई (ग्रेन)",
        "pieceQuantityLabel": "कितने पीस:", "addPieceBtn": "पीस जोड़ें",
        "addedPiecesTitle": "जोड़े गए पीस", "tableName": "नाम", "tableWidth": "चौड़ाई",
        "tableLength": "लंबाई", "tableQuantity": "संख्या", "tableRemove": "हटाएं",
        "totalPiecesInList": "कुल पीस लिस्ट में:",
        "calculateLayoutBtn": "लेआउट की गणना करें (डिफ़ॉल्ट)", "resetCurrentBtn": "रीसेट (वर्तमान)",
        "resultsTitle": "परिणाम", "totalSheetsDefault": "कुल आवश्यक शीट्स: 0",
        "sheetSettingsTitle": "शीट सेटिंग्स",
        "sheetNameLabel": "शीट का नाम (वैकल्पिक):",
        "sheetNamePlaceholder": "उदा: प्लायवुड 8x4",
        "sheetWidthLabel": "शीट की चौड़ाई",
        "sheetLengthGrainLabel": "शीट की लंबाई (ग्रेन)", "respectGrainLabel": "ग्रेन की दिशा का ध्यान रखें",
        "applyAndSaveBtn": "लागू करें और सेव करें", "historyTitle": "हिस्ट्री",
        "historyNote": "नोट: यह केवल पिछले कुछ बदलावों को दिखाता है। किसी आइटम पर क्लिक करके उसे लोड करें।",
        "noHistory": "कोई हिस्ट्री उपलब्ध नहीं है।", "historyStatusPrefix": "स्थिति #", "historyPiecesSuffix": " पीस",
        "historyNoPieces": "कोई पीस नहीं", "historySheetNamePrefix": "शीट: ",
        "alert_invalidPositiveNumbers": "कृपया सभी पीस के लिए मान्य सकारात्मक संख्याएँ दर्ज करें।",
        "alert_pieceTooLarge": "पीस \"{name}\" ({width}×{length}) शीट ({sheetW}×{sheetL}){grainText}{sheetNameText} फिट नहीं हो सकता।",
        "alert_noDataToExport": "एक्सपोर्ट/प्रिंट करने के लिए कोई डेटा नहीं है।",
        "alert_selectValidJson": "कृपया एक मान्य JSON फ़ाइल चुनें।",
        "alert_jsonImportSuccess": "डेटा JSON फ़ाइल से सफलतापूर्वक इम्पोर्ट किया गया!",
        "alert_jsonFormatError": "JSON फ़ाइल का प्रारूप सही नहीं है।", "alert_jsonParseError": "JSON फ़ाइल पार्स करने में त्रुटि हुई।",
        "alert_confirmClearStorage": "क्या आप वाकई localStorage में सेव किए गए सभी डेटा (हिस्ट्री और प्रोजेक्ट्स सहित) को हटाना चाहते हैं?",
        "alert_storageCleared": "localStorage से सेव किया हुआ डेटा सफलतापूर्वक हटा दिया गया है।",
        "alert_confirmResetCurrent": "क्या आप वाकई वर्तमान डेटा और लेआउट रीसेट करना चाहते हैं?",
        "alert_historyLoaded": "हिस्ट्री से स्थिति लोड की गई।",
        "alert_calculateLayoutFirst": "पहले लेआउट की गणना करें।",
        "alert_calculateLayoutFirstForPrint": "छापने/PDF बनाने के लिए पहले लेआउट की गणना करें।",
        "alert_layoutForPrint": "लेआउट देखने के लिए \"लेआउट की गणना करें और दिखाएं\" पर क्लिक करें।",
        "alert_sheetSettingsUpdated": "शीट सेटिंग्स अपडेट की गईं।", "totalSheetsResult": "कुल आवश्यक शीट्स: {count}",
        "sheetTitlePrefix": "शीट", "grainedSheetSuffix": "(ग्रेन वाली)", "noGrainSheetSuffix": "(बिना ग्रेन)",
        "sheetDisplayName": " ({name})",
        "unitSettingsTitle": "यूनिट सेटिंग्स", "selectUnitLabel": "वर्तमान यूनिट चुनें:", "applyBtn":"लागू करें",
        "alert_unitChanged":"यूनिट {unit} में बदल दी गई है। मौजूदा मान रूपांतरित कर दिए गए हैं।",
        "alert_invalidSheetSize": "कृपया मान्य शीट आकार दर्ज करें।",
        "alert_pieceTooLargeSheet": "पीस \"{name}\" ({width}×{length} {unit}) शीट #{sheetNum} पर फिट नहीं हो सका। कृपया पीस या शीट का आकार जांचें।",
        "alert_layoutHang": "लेआउट गणना में बहुत अधिक समय लग रहा है। कृपया पीसों की संख्या या आकार जांचें।",
        "alert_workerCreationError": "वेब वर्कर बनाने में त्रुटि हुई। ब्राउज़र इसे सपोर्ट नहीं कर सकता है या कोई सुरक्षा नीति इसे रोक रही है।",
        "calculatingLayout": "लेआउट की गणना हो रही है...",
        "sheetsTitle": "शीट्स",
        "cuttingListTitle": "कटिंग लिस्ट:", "totalPiecesOnSheet": "इस शीट पर कुल पीस: {count}",
        "wastageReportTitle": "वेस्टेज रिपोर्ट",
        "sheetWastageTitle": "शीट #{id} वेस्टेज:", "totalWastageRectsOnSheet": "इस शीट पर कुल वेस्टेज टुकड़े: {count}",
        "totalAreaUsed": "उपयोग किया गया कुल क्षेत्र:",
        "totalFreeArea": "कुल खाली क्षेत्र (वेस्टेज):",
        "wastagePercentage": "वेस्टेज प्रतिशत:",
        "noFreeRects": "कोई उपयोगी वेस्टेज नहीं (या बहुत छोटा)।",
        "totalWastagePiecesOverall": "कुल अन्य वेस्टेज टुकड़े: {count}", 
        "deleteHistoryEntryConfirm": "क्या आप वाकई इस हिस्ट्री एंट्री को हटाना चाहते हैं?",
        "loadingPdf": "प्रिंट के लिए तैयारी...", 
        "projectManagementTitle": "प्रोजेक्ट मैनेजमेंट",
        "saveCurrentProjectTitle": "वर्तमान प्रोजेक्ट सेव करें",
        "projectNameLabel": "प्रोजेक्ट का नाम:",
        "projectNamePlaceholder": "उदा: किचन कैबिनेट, बुकशेल्फ",
        "saveProjectBtn": "प्रोजेक्ट सेव करें",
        "savedProjectsTitle": "सेव किए गए प्रोजेक्ट्स",
        "loadProjectBtn": "लोड करें",
        "deleteProjectBtn": "हटाएं",
        "noProjectsSaved": "कोई प्रोजेक्ट सेव नहीं किया गया है।",
        "alert_projectNameMissing": "कृपया प्रोजेक्ट का नाम दर्ज करें।",
        "alert_projectSaved": "प्रोजेक्ट '{name}' सफलतापूर्वक सेव किया गया!",
        "alert_projectLoaded": "प्रोजेक्ट '{name}' सफलतापूर्वक लोड किया गया!",
        "alert_projectDeleted": "प्रोजेक्ट '{name}' सफलतापूर्वक हटाया गया!",
        "confirmDeleteProject": "क्या आप वाकई प्रोजेक्ट '{name}' को हटाना चाहते हैं?"
    },
    "en": { /* ... (आपकी सभी अंग्रेजी स्ट्रिंग्स यहाँ) ... */ }
};
